import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve, relative } from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
const cli = fileURLToPath(new URL('../bin/open-jarvis.mjs', import.meta.url));
test('CLI migration preserves saved preferences before activation and reports conflicts without writes', t => {
  const root = mkdtempSync(join(tmpdir(), 'jarvis-migration-cli-'));
  t.after(() => { assert.ok(relative(resolve(tmpdir()), root).startsWith('jarvis-migration-cli-')); rmSync(root, {recursive:true, force:true}); });
  const source = join(root, 'source'), target = join(root, 'target');
  mkdirSync(join(source, 'jarvis'), {recursive:true});
  const model = {terra:{model:'gpt-6-sol',effort:'low',fast:true}};
  writeFileSync(join(source, 'jarvis/models.json'), JSON.stringify(model));
  const run = (home, ...args) => spawnSync(process.execPath, [cli,...args,'--home',home,'--json'], {encoding:'utf8',timeout:20000});
  const ok = result => { assert.equal(result.status,0,result.stderr); return JSON.parse(result.stdout); };
  assert.equal(ok(run(source,'employees','--init','--yes')).created.length,4);
  const bundle = join(root, 'bundle.gz');
  ok(run(source,'export','--out',bundle));
  assert.equal(ok(run(target,'import','--from',bundle)).status,'preview');
  assert.equal(existsSync(target),false);
  ok(run(target,'import','--from',bundle,'--yes'));
  assert.deepEqual(JSON.parse(readFileSync(join(target,'jarvis/models.json'),'utf8')),model);
  assert.equal(ok(run(target,'import','--from',bundle,'--yes')).writtenCount,0);
  ok(run(target,'install','--models',join(target,'jarvis/models.json'),'--yes'));
  const plan = ok(run(target,'plan','--employee','atlas-backend','--difficulty','standard'));
  assert.deepEqual(plan.requested,{model:'gpt-6-sol',effort:'low',speed:'fast'});
  assert.equal(plan.dispatched,false);
  const blocked = run(target,'plan','--employee','iris-frontend','--difficulty','light','--skill','interface-design');
  assert.equal(blocked.status,1); assert.equal(JSON.parse(blocked.stdout).status,'blocked');
  writeFileSync(join(target,'jarvis/employees/atlas-backend.md'),'existing user card');
  const conflict = run(target,'import','--from',bundle,'--yes');
  assert.equal(conflict.status,1); assert.equal(JSON.parse(conflict.stdout).writtenCount,0);
  assert.equal(readFileSync(join(target,'jarvis/employees/atlas-backend.md'),'utf8'),'existing user card');
  assert.equal(run(source,'export','--out',bundle).status,1);
});
